### ISSUE TITLE
Backspace is occasionally inoperative.

### ISSUE THREAD

**Issue by rokejulianlockhart** [SimpleMobileTools/Simple-Keyboard#40]
I must focus something alternative before the key operates again. It persists until that.

**Comment by tibbi** [comment]
how to reproduce it?

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@tibbi, it appears to be random.

**Comment by tibbi** [comment]
needs more info on how to reproduce it

**Comment by haplorhine** [comment]
## Examples of backspace problems with Simple-Keyboard or OpenBoard
In certain texteditors like this [example from freeCodeCamp](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/storing-values-with-the-assignment-operator) tapping backspace on Simple-Keyboard, doesn't delete whitespace.
It also isn't possible to delete an empty line with Simple-Keyboard. The cursor stays at the beginning of the line when tapping backspace in an empty line. With Gboard it is possible to delete everything.

![Screenshot_20230708-150457__01__01](https://github.com/SimpleMobileTools/Simple-Keyboard/assets/36515150/3012ff78-fee7-4760-a371-fb873f6661ab)

When trying different Keyboards with a [Key Event Test App](https://unixpapa.com/js/testkey.html) it appears that Gboard sends a keyCode 8 "Backspace" event in empty input fields and keyCode 229 "Process" in non-empty fields. Simple-Keyboard doesn't seem to trigger an event in empty input fields.
![Screenshot_20230708-150118__01__01](https://github.com/SimpleMobileTools/Simple-Keyboard/assets/36515150/34c9ad58-8d44-4fc9-89d8-6c8c04a8c2fb)

![Screenshot_20230708-150628__01](https://github.com/SimpleMobileTools/Simple-Keyboard/assets/36515150/7a331d1f-15d5-4aff-b057-bbadf0dab9bf)

**Comment by tibbi** [comment]
it works just fine in casually used apps, that sample is some very weird code, not really something you meet in the real world

**Comment by haplorhine** [comment]
Yes it works fine in most circumstances.
There are just problems in some apps for example Logseq on android where it isn't possible to delete bullet points with Simple-Keyboard [(https://github.com/logseq/logseq/issues/4430)](https://github.com/logseq/logseq/issues/4430) (it works with Gboard or Typewise) so I tried to find out the reason. Also in this test [https://dvcs.w3.org/hg/d4e/raw-file/tip/key-event-test.html](https://dvcs.w3.org/hg/d4e/raw-file/tip/key-event-test.html) Simple-Keyboard doesn't trigger an event when tapping backspace. When using other Keyboards like Typewise or Gboard the mentioned event tester registers "Backspace".
Since I would prefer to use Simple-Keyboard for all apps I wondered if it would be possible to provide this functionality or if this is not feasible.
