### ISSUE TITLE
Add Bulgarian language 

### ISSUE THREAD

**Issue by chobster** [SimpleMobileTools/Simple-Keyboard#66]
Hello guys, I love your project and I've been getting increasing number of apps made from you. I love the simple concept and the keyboard is the next amazing thing that I felt I always needed when working on my phone. I would really appreciate it if you can add Bulgarian language as well.

**Comment by smaragdus** [comment]
1+ for Bulgarian,

**Comment by Naveen3Singh** [comment]
All right, I'm working on adding the Bulgarian language. 
As I am not a native speaker, in case any of you are willing to check if everything is correct, [here's a test apk with Bulgarian language support](https://github.com/Naveen3Singh/Simple-Keyboard/releases/download/test_release_apk/keyboard-prepaid-debug.apk)

APK is not production ready, pls uninstall afterward.

**Comment by chobster** [comment]
Hi Naveen,

Thank you for the work so far! 😃 I will be testing the apk you send and give you some feedback after.

**Comment by chobster** [comment]
Looks good so far. The letters are all here so I don't have complaints. 
Once again, thank you for your awesome work!
😀

**Comment by tibbi** [comment]
guess it has been added already

**Comment by smaragdus** [comment]
Hello, I tested version [5.3.2](https://github.com/SimpleMobileTools/Simple-Keyboard/releases/tag/5.3.2) but it turned out to be Bulgarian Phonetic layout. I am used to Bulgarian BDS layout (Bulgarian National Standard) so the current layout (phonetic) is inconvenient for me. I would suggest adding a new layout:

- **Bulgarian (BDS)**

while the current layout may be renamed to:

- **Bulgarian (Phonetic)**

I suppose I am not the only one who prefers the BDS layout (the standard layout for Bulgarian).
